-- Seed public.vehicles from the placeholder dataset.
--
-- Generated by scripts/generate_seed_sql.mjs. Do not hand-edit: regenerate.
--
-- Run this in the Supabase SQL editor AFTER 0001_vehicles.sql.
--
-- NOTE ON IMAGES: `image` holds local /vehicles/... paths rather than Storage
-- URLs. That is deliberate — the photos had not been uploaded when this was
-- generated, and a local path resolves correctly the moment the data layer is
-- switched over. Rewrite these to public URLs later by running the --storage
-- variant, which writes supabase/seed-storage.sql.

insert into public.vehicles (id, make, model, variant, year, price, mileage, transmission, fuel, body_type, registration_city, status, image, image_alt, highlight, description, gallery, featured, published)
values
  ('toyota-corolla-altis-grande-2021', 'Toyota', 'Corolla', 'Altis Grande 1.8', 2021, 8650000, 42000, 'Automatic', 'Petrol', 'Sedan', 'Islamabad', 'available', '/vehicles/corolla-altis.jpg', 'Black Toyota Corolla Altis Grande sedan parked outdoors, front three-quarter view', 'Single owner, complete service history', 'The Altis Grande is the top trim in the Corolla range, and this 2021 car carries the 1.8-litre engine the badge names, paired with an automatic gearbox. It has covered 42,000 km and is registered in Islamabad. A four-door sedan — this is the version of the Corolla that came with the most equipment as standard.', '{}'::text[], true, true),
  ('honda-civic-oriel-2022', 'Honda', 'Civic', 'Oriel', 2022, 10400000, 31000, 'Automatic', 'Petrol', 'Sedan', 'Rawalpindi', 'available', '/vehicles/civic-oriel.jpg', 'Grey Honda Civic sedan parked on a residential street, rear view', 'Low mileage, original paint', 'Oriel is the highest trim in the Civic range. This 2022 car is automatic and petrol, has covered 31,000 km, and is registered in Rawalpindi. A sedan, and the newest model year currently in stock.', '{}'::text[], true, true),
  ('toyota-fortuner-sigma-4-2019', 'Toyota', 'Fortuner', 'Sigma 4', 2019, 16750000, 78000, 'Automatic', 'Diesel', 'SUV', 'Islamabad', 'available', '/vehicles/fortuner-sigma.jpg', 'Black Toyota Fortuner SUV parked beside trees', '4x4 diesel, well maintained', 'The Sigma 4 is the four-wheel-drive Fortuner, and this 2019 car is the diesel. Automatic, 78,000 km, registered in Islamabad. A full-size SUV — this is the model people buy here when the route includes unpaved roads and a loaded vehicle.', '{}'::text[], true, true),
  ('toyota-land-cruiser-prado-tx-2017', 'Toyota', 'Land Cruiser Prado', 'TX', 2017, 24500000, 96000, 'Automatic', 'Petrol', 'SUV', 'Islamabad', 'available', '/vehicles/prado-tx.jpg', 'Black Toyota Land Cruiser Prado SUV on a mountain road at dusk', 'Imported, accident-free', 'The TX is the higher of the two Prado trims. This 2017 car is petrol and automatic, showing 96,000 km with Islamabad registration. A full-size four-wheel-drive SUV, and the most expensive car currently on the lot.', '{}'::text[], true, true),
  ('suzuki-swift-glx-2020', 'Suzuki', 'Swift', 'GLX CVT', 2020, 4150000, 55000, 'Automatic', 'Petrol', 'Hatchback', 'Wah Cantt', 'available', '/vehicles/swift-glx.jpg', 'Blue Suzuki Swift hatchback parked on a hillside road', 'Economical daily driver', 'The GLX is the top Swift trim, and this one is the CVT automatic rather than the manual. A 2020 car, petrol, 55,000 km, registered in Wah Cantt. A hatchback — compact, easy to park, and economical on a daily commute.', '{}'::text[], true, true),
  ('kia-picanto-2021', 'Kia', 'Picanto', '1.0 A/T', 2021, 3650000, 38000, 'Automatic', 'Petrol', 'Hatchback', 'Rawalpindi', 'reserved', '/vehicles/kia-picanto.jpg', 'White Kia Picanto hatchback parked on a paved surface, front view', 'Ideal first car, low running cost', 'The Picanto is the smallest car we keep, and it is a city hatchback rather than a long-distance car. This 2021 example is the 1.0-litre automatic, petrol, with 38,000 km and Rawalpindi registration. Currently reserved — message us and we will tell you if it becomes available again.', '{}'::text[], true, true),
  ('suzuki-ciaz-glx-2019', 'Suzuki', 'Ciaz', '1.4 GLX', 2019, 4850000, 62000, 'Automatic', 'Petrol', 'Sedan', 'Islamabad', 'available', '/vehicles/suzuki-ciaz.jpg', 'Silver Suzuki Ciaz sedan parked on a street, rear three-quarter view', 'Roomy sedan, economical to run', 'The Ciaz is the larger of Suzuki''s two sedans, and the 1.4 GLX is the top trim. This 2019 car is automatic and petrol, with 62,000 km and Islamabad registration. A sedan with a proper boot — which is the main thing buyers step up from a hatchback for.', '{}'::text[], false, true),
  ('suzuki-jimny-glx-2021', 'Suzuki', 'Jimny', '1.5 GLX', 2021, 8200000, 28000, 'Automatic', 'Petrol', 'SUV', 'Islamabad', 'available', '/vehicles/suzuki-jimny.jpg', 'Yellow Suzuki Jimny compact 4x4 parked on a street, front view', '4x4, imported, low mileage', 'The Jimny is a small ladder-frame four-wheel drive — a different proposition from the crossover SUVs it usually gets compared with. This 2021 car is the 1.5 GLX, automatic and petrol, with 28,000 km and Islamabad registration.', '{}'::text[], false, true),
  ('suzuki-vitara-gl-plus-2018', 'Suzuki', 'Vitara', '1.6 GL+', 2018, 6400000, 71000, 'Automatic', 'Petrol', 'SUV', 'Rawalpindi', 'available', '/vehicles/suzuki-vitara.jpg', 'Silver Suzuki Vitara SUV standing in an open field under a cloudy sky', 'Imported, well maintained', 'The Vitara is Suzuki''s compact crossover and GL+ is the higher of its two trims. This 2018 car is the 1.6-litre automatic, petrol, 71,000 km, registered in Rawalpindi. It sits between a hatchback and a full SUV: raised seating position and more space, without the running costs of a large four-wheel drive.', '{}'::text[], false, true),
  ('suzuki-grand-vitara-2015', 'Suzuki', 'Grand Vitara', '2.4', 2015, 5300000, 118000, 'Manual', 'Petrol', 'SUV', 'Taxila', 'available', '/vehicles/suzuki-grand-vitara.jpg', 'Silver Suzuki Grand Vitara SUV with a front bull bar parked in a grassy field', 'Genuine 4x4, ready for rough roads', 'The Grand Vitara is the older, body-on-frame Suzuki SUV — a proper four-wheel drive rather than a crossover. This 2015 car is the 2.4-litre petrol with a manual gearbox, showing 118,000 km and registered in Taxila. The highest-mileage car on the lot.', '{}'::text[], false, true),
  ('honda-city-aspire-2019', 'Honda', 'City', '1.5 Aspire', 2019, 6150000, 71000, 'Automatic', 'Petrol', 'Sedan', 'Taxila', 'sold', '/vehicles/city-aspire.jpg', 'White Honda City sedan parked outdoors, rear view', null, 'The Aspire is the top trim of the City. This 2019 car was the 1.5-litre automatic, petrol, with 71,000 km and Taxila registration. It has since been sold.', '{}'::text[], false, true),
  ('hyundai-kona-2019', 'Hyundai', 'Kona', 'FWD', 2019, 7400000, 44000, 'Automatic', 'Petrol', 'Crossover', 'Islamabad', 'sold', '/vehicles/hyundai-kona.jpg', 'Black Hyundai Kona crossover on a road in fog with headlights on', null, 'The Kona is Hyundai''s compact crossover. This 2019 front-wheel-drive example was automatic and petrol, with 44,000 km and Islamabad registration. It has since been sold.', '{}'::text[], false, true),
  ('toyota-hilux-revo-2020', 'Toyota', 'Hilux', 'Revo G', 2020, 12900000, 63000, 'Manual', 'Diesel', 'Pickup', 'Attock', 'sold', '/vehicles/hilux-revo.jpg', 'Silver Toyota Hilux double-cab pickup parked on a tree-lined street', null, 'The Revo G is the double-cab Hilux in the higher trim. This 2020 car was the diesel with a manual gearbox, 63,000 km, registered in Attock. It has since been sold.', '{}'::text[], false, true),
  ('bmw-x3-xdrive30i-2018', 'BMW', 'X3', 'xDrive30i', 2018, 18900000, 52000, 'Automatic', 'Petrol', 'SUV', 'Islamabad', 'sold', '/vehicles/bmw-x3.jpg', 'Black BMW X3 SUV parked outdoors, front three-quarter view', null, 'The xDrive30i is the petrol X3 with all-wheel drive. This 2018 car was automatic, 52,000 km, registered in Islamabad. It has since been sold.', '{}'::text[], false, true)
on conflict (id) do update set
  make = excluded.make,
  model = excluded.model,
  variant = excluded.variant,
  year = excluded.year,
  price = excluded.price,
  mileage = excluded.mileage,
  transmission = excluded.transmission,
  fuel = excluded.fuel,
  body_type = excluded.body_type,
  registration_city = excluded.registration_city,
  status = excluded.status,
  image = excluded.image,
  image_alt = excluded.image_alt,
  highlight = excluded.highlight,
  description = excluded.description,
  gallery = excluded.gallery,
  featured = excluded.featured,
  published = excluded.published;
