-- Point the seeded rows at their Supabase Storage URLs.
--
-- Generated by scripts/generate_seed_sql.mjs --storage. Do not hand-edit.
--
-- Run this in the Supabase SQL editor only AFTER the vehicle-photos bucket exists AND
-- all 14 photos have been uploaded to it. Run it before the photos are up and
-- every image on the site 404s. Check first with:
--
--     node --env-file=.env.local qa/probe-supabase.mjs
--
-- That probe fails loudly while any photo is missing, which is the gate for
-- this file.
--
-- Before this runs, the rows reference /vehicles/... paths in public/ — which is
-- correct but interim.

update public.vehicles set image = 'https://wlwnfgtrilzikdyigctu.supabase.co/storage/v1/object/public/vehicle-photos/corolla-altis.jpg' where id = 'toyota-corolla-altis-grande-2021';
update public.vehicles set image = 'https://wlwnfgtrilzikdyigctu.supabase.co/storage/v1/object/public/vehicle-photos/civic-oriel.jpg' where id = 'honda-civic-oriel-2022';
update public.vehicles set image = 'https://wlwnfgtrilzikdyigctu.supabase.co/storage/v1/object/public/vehicle-photos/fortuner-sigma.jpg' where id = 'toyota-fortuner-sigma-4-2019';
update public.vehicles set image = 'https://wlwnfgtrilzikdyigctu.supabase.co/storage/v1/object/public/vehicle-photos/prado-tx.jpg' where id = 'toyota-land-cruiser-prado-tx-2017';
update public.vehicles set image = 'https://wlwnfgtrilzikdyigctu.supabase.co/storage/v1/object/public/vehicle-photos/swift-glx.jpg' where id = 'suzuki-swift-glx-2020';
update public.vehicles set image = 'https://wlwnfgtrilzikdyigctu.supabase.co/storage/v1/object/public/vehicle-photos/kia-picanto.jpg' where id = 'kia-picanto-2021';
update public.vehicles set image = 'https://wlwnfgtrilzikdyigctu.supabase.co/storage/v1/object/public/vehicle-photos/suzuki-ciaz.jpg' where id = 'suzuki-ciaz-glx-2019';
update public.vehicles set image = 'https://wlwnfgtrilzikdyigctu.supabase.co/storage/v1/object/public/vehicle-photos/suzuki-jimny.jpg' where id = 'suzuki-jimny-glx-2021';
update public.vehicles set image = 'https://wlwnfgtrilzikdyigctu.supabase.co/storage/v1/object/public/vehicle-photos/suzuki-vitara.jpg' where id = 'suzuki-vitara-gl-plus-2018';
update public.vehicles set image = 'https://wlwnfgtrilzikdyigctu.supabase.co/storage/v1/object/public/vehicle-photos/suzuki-grand-vitara.jpg' where id = 'suzuki-grand-vitara-2015';
update public.vehicles set image = 'https://wlwnfgtrilzikdyigctu.supabase.co/storage/v1/object/public/vehicle-photos/city-aspire.jpg' where id = 'honda-city-aspire-2019';
update public.vehicles set image = 'https://wlwnfgtrilzikdyigctu.supabase.co/storage/v1/object/public/vehicle-photos/hyundai-kona.jpg' where id = 'hyundai-kona-2019';
update public.vehicles set image = 'https://wlwnfgtrilzikdyigctu.supabase.co/storage/v1/object/public/vehicle-photos/hilux-revo.jpg' where id = 'toyota-hilux-revo-2020';
update public.vehicles set image = 'https://wlwnfgtrilzikdyigctu.supabase.co/storage/v1/object/public/vehicle-photos/bmw-x3.jpg' where id = 'bmw-x3-xdrive30i-2018';
