/**
 * Generate `supabase/seed.sql` from the placeholder dataset.
 *
 *     node --experimental-strip-types scripts/generate_seed_sql.mjs
 *     node --experimental-strip-types scripts/generate_seed_sql.mjs --storage
 *
 * Why this exists rather than hand-written INSERTs: the dataset carries 14
 * records with long `description` strings and apostrophe-bearing copy. Hand
 * writing that into SQL means 14 chances to misplace a quote, and the failure
 * would be a syntax error at paste time or — worse — silently wrong text. This
 * imports the real module, so the seed cannot disagree with the app.
 *
 * `--experimental-strip-types` lets Node import the `.ts` data file directly.
 * The alternative is re-implementing a TypeScript parser in a script, which is
 * how you end up with a seed that quietly drops a record.
 *
 * Two modes, writing two different files:
 *
 *   (default)  -> supabase/seed.sql
 *              `image` is the local `/vehicles/...` path. Correct while the
 *              photos are still in `public/`, so the site works immediately
 *              after the data layer is swapped.
 *   --storage  -> supabase/seed-storage.sql
 *              `image` is the Supabase Storage public URL. Run this once the
 *              bucket exists and the photos have been uploaded; it emits
 *              UPDATEs rather than INSERTs, since the rows already exist.
 *
 * The two modes deliberately write to *different* files. They used to share
 * one, which meant merely previewing the --storage output silently replaced the
 * canonical seed with statements that pointed at photos that were not uploaded
 * yet — running the file afterwards would have broken every image on the site.
 * A command whose whole purpose is to be inspected must not destroy the thing
 * it is replacing.
 *
 * One-time tool. When `src/data/vehicles.ts` is deleted, delete this with it.
 */

import { writeFileSync } from "node:fs";
import path from "node:path";

import { vehicles } from "../src/data/vehicles.ts";

const useStorage = process.argv.includes("--storage");
const BUCKET = "vehicle-photos";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
if (useStorage && !supabaseUrl) {
  console.error(
    "NEXT_PUBLIC_SUPABASE_URL is not set. Run with:\n" +
      "  node --env-file=.env.local --experimental-strip-types scripts/generate_seed_sql.mjs --storage",
  );
  process.exit(1);
}

const storageBase = supabaseUrl ? `${supabaseUrl}/storage/v1/object/public/${BUCKET}` : "";

/** SQL string literal, or NULL. Doubles any embedded quote. */
const q = (value) =>
  value === null || value === undefined ? "null" : `'${String(value).replace(/'/g, "''")}'`;

/** Postgres int4 literal — strips the TS numeric separators (8_650_000). */
const n = (value) => String(value).replace(/_/g, "");

const imageFor = (vehicle) =>
  useStorage ? `${storageBase}/${path.basename(vehicle.image)}` : vehicle.image;

const COLUMNS = [
  "id",
  "make",
  "model",
  "variant",
  "year",
  "price",
  "mileage",
  "transmission",
  "fuel",
  "body_type",
  "registration_city",
  "status",
  "image",
  "image_alt",
  "highlight",
  "description",
  "gallery",
  "featured",
  "published",
];

function values(vehicle) {
  return [
    q(vehicle.id),
    q(vehicle.make),
    q(vehicle.model),
    q(vehicle.variant),
    n(vehicle.year),
    n(vehicle.price),
    n(vehicle.mileage),
    q(vehicle.transmission),
    q(vehicle.fuel),
    q(vehicle.bodyType),
    q(vehicle.registrationCity),
    q(vehicle.status),
    q(imageFor(vehicle)),
    q(vehicle.imageAlt),
    q(vehicle.highlight),
    q(vehicle.description),
    vehicle.gallery?.length
      ? `array[${vehicle.gallery.map(q).join(", ")}]::text[]`
      : `'{}'::text[]`,
    vehicle.featured === true ? "true" : "false",
    /* published = true, so the rows are actually visible. The column defaults
       to false precisely so that a draft cannot leak; the seed is the one place
       that has to opt in. */
    "true",
  ].join(", ");
}

const header = useStorage
  ? `-- Point the seeded rows at their Supabase Storage URLs.
--
-- Generated by scripts/generate_seed_sql.mjs --storage. Do not hand-edit.
--
-- Run this in the Supabase SQL editor only AFTER the ${BUCKET} bucket exists AND
-- all 14 photos have been uploaded to it. Run it before the photos are up and
-- every image on the site 404s. Check first with:
--
--     node --env-file=.env.local qa/probe-supabase.mjs
--
-- That probe fails loudly while any photo is missing, which is the gate for
-- this file.
--
-- Before this runs, the rows reference /vehicles/... paths in public/ — which is
-- correct but interim.`
  : `-- Seed public.vehicles from the placeholder dataset.
--
-- Generated by scripts/generate_seed_sql.mjs. Do not hand-edit: regenerate.
--
-- Run this in the Supabase SQL editor AFTER 0001_vehicles.sql.
--
-- NOTE ON IMAGES: \`image\` holds local /vehicles/... paths rather than Storage
-- URLs. That is deliberate — the photos had not been uploaded when this was
-- generated, and a local path resolves correctly the moment the data layer is
-- switched over. Rewrite these to public URLs later by running the --storage
-- variant, which writes supabase/seed-storage.sql.`;

const body = useStorage
  ? vehicles
      .map(
        (v) =>
          `update public.vehicles set image = ${q(imageFor(v))} where id = ${q(v.id)};`,
      )
      .join("\n")
  : `insert into public.vehicles (${COLUMNS.join(", ")})\nvalues\n` +
    vehicles.map((v) => `  (${values(v)})`).join(",\n") +
    `\non conflict (id) do update set\n` +
    COLUMNS.filter((c) => c !== "id")
      .map((c) => `  ${c} = excluded.${c}`)
      .join(",\n") +
    `;`;

const out = `${header}\n\n${body}\n`;
const filename = useStorage ? "seed-storage.sql" : "seed.sql";
const target = path.resolve(import.meta.dirname, "..", "supabase", filename);
writeFileSync(target, out, "utf8");

console.log(`${useStorage ? "Storage URL" : "Seed"} SQL written: ${target}`);
console.log(`  ${vehicles.length} record(s), ${out.length} bytes`);
console.log(`  image mode: ${useStorage ? "Supabase Storage public URLs" : "local /vehicles/ paths"}`);
